In [24]:
import pandas as pd
import re

In [25]:
df = pd.read_csv('./data/sms-spam-collection-a-more-diverse-dataset.csv', encoding='latin-1')
df.describe()

             label
count  5574.000000
mean      0.134015
std       0.340699
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [26]:
df.rename(columns={'sms': 'text'}, inplace=True)
df.head()

                                                text  label
0  Go until jurong point, crazy.. Available only ...      0
1                    Ok lar... Joking wif u oni...\n      0
2  Free entry in 2 a wkly comp to win FA Cup fina...      1
3  U dun say so early hor... U c already then say...      0
4  Nah I don't think he goes to usf, he lives aro...      0

In [27]:
# df.replace({'label': {'ham': 0, 'spam': 1}}, inplace=True)
df['text'] = df['text'].str.lower()
df.head()

                                                text  label
0  go until jurong point, crazy.. available only ...      0
1                    ok lar... joking wif u oni...\n      0
2  free entry in 2 a wkly comp to win fa cup fina...      1
3  u dun say so early hor... u c already then say...      0
4  nah i don't think he goes to usf, he lives aro...      0

In [28]:
def remove_url(text):
    new_text = re.sub(r'(?:https?://|http//|www\.|wap\.|\.wml\b|\.com\b|\.co\b|\.tv\b|\.ac\b)', '', text)
    new_text = re.sub(r'(lt|gt|amp|quot|#39|#34|nbsp|&lt|&gt|&amp|&quot|&#39|&#34|&nbsp)', '', new_text)
    return new_text

df['text'] = df['text'].apply(remove_url)
df.head()

                                                text  label
0  go until jurong point, crazy.. available only ...      0
1                    ok lar... joking wif u oni...\n      0
2  free entry in 2 a wkly comp to win fa cup fina...      1
3  u dun say so early hor... u c already then say...      0
4  nah i don't think he goes to usf, he lives aro...      0

In [29]:
df['text'] = df['text'].str.replace(r'\d{4,10}', '', regex=True)
df['text'] = df['text'].str.replace(r'to\s\d{4,}', '', regex=True)
df.head()

                                                text  label
0  go until jurong point, crazy.. available only ...      0
1                    ok lar... joking wif u oni...\n      0
2  free entry in 2 a wkly comp to win fa cup fina...      1
3  u dun say so early hor... u c already then say...      0
4  nah i don't think he goes to usf, he lives aro...      0

In [30]:
df['text'] = df['text'].str.replace(r'[^A-Za-z0-9]', ' ', regex=True)
df['text'] = df['text'].str.replace(r'\s+', ' ', regex=True)
df['text'] = df['text'].str.strip()
df = df[df['text'] != '']
df.head()

                                                text  label
0  go until jurong point crazy available only in ...      0
1                            ok lar joking wif u oni      0
2  free entry in 2 a wkly comp to win fa cup fina...      1
3        u dun say so early hor u c already then say      0
4  nah i don t think he goes to usf he lives arou...      0

In [31]:
df.to_csv('./data/spam_test_preprocessed.csv', index=False)