In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('./data/spam.csv', encoding='latin-1')
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df.rename(columns={'v1': 'label', 'v2': 'text'}, inplace=True)
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.replace({'label': {'ham': 0, 'spam': 1}}, inplace=True)
df['text'] = df['text'].str.lower()
df.head()

  label                                               text
0     0  go until jurong point, crazy.. available only ...
1     0                      ok lar... joking wif u oni...
2     1  free entry in 2 a wkly comp to win fa cup fina...
3     0  u dun say so early hor... u c already then say...
4     0  nah i don't think he goes to usf, he lives aro...

In [ ]:
df['text'] = df['text'].str.replace(r'\d{4,10}', '', regex=True)
df['text'] = df['text'].str.replace(r'to\s\d{4,}', '', regex=True)
df.head()

  label                                               text
0     0  go until jurong point crazy available only in ...
1     0                           ok lar joking wif u oni
2     1  free entry in 2 a wkly comp to win fa cup fina...
3     0       u dun say so early hor u c already then say
4     0  nah i don t think he goes to usf he lives arou...

In [24]:
df['text'] = df['text'].str.replace(r'[^A-Za-z0-9]', ' ', regex=True)
df['text'] = df['text'].str.replace(r'\s+', ' ', regex=True)
df['text'] = df['text'].str.strip()
df.head()

  label                                               text
0     0  go until jurong point crazy available only in ...
1     0                            ok lar joking wif u oni
2     1  free entry in 2 a wkly comp to win fa cup fina...
3     0        u dun say so early hor u c already then say
4     0  nah i don t think he goes to usf he lives arou...

In [25]:
df.to_csv('./data/spam_preprocessed.csv', index=False)